peerwire/news/urls.py
from django.conf.urls import patterns, include, url

from news import views
from news.feeds import NewsFeed

urlpatterns = patterns('news.views',
    url(r'^$', 'index', name='index'),
    url(r'^(\d+)/$', 'newspage', name='newspage'),
    url(r'^f/$', NewsFeed(), name='newsfeed'),
    )

peerwire/peerwire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView

from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

sqs = SearchQuerySet().facet('status').facet('seeking').facet('level')

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^a/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^a/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^a/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^a/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^a/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^a/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    # url(r'^a/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm_uidb36,
    #     name='password_reset_confirm'),
    url(r'^a/', include('registration.backends.default.urls')),
    url(r'^s/$', FacetedSearchView(
        form_class=FacetedSearchForm,
        searchqueryset=sqs
        ), name='haystack_search'),
    url(r'^s/', include('haystack.urls', namespace='haystack')),
    url(r'^n/', include('news.urls', namespace='news')),
    url(r'^r/', include('reporting.urls', namespace='reporting')),
    url(r'^', include('projects.urls', namespace='projects')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peerwire/projects/urls.py
from django.conf.urls import patterns, include, url

from projects import views

urlpatterns = patterns('projects.views',
    url(r'^$', 'index', name='index'),
    url(r'^p/(\d+)/$', 'projectpage', name='projectpage'),
    url(r'^u/(\d+)/$', 'profilepage', name='profilepage'),
    url(r'^u/(\d+)/d/$', 'delete_profile', name='delete_profile'),
    url(r'^u/(\d+)/d/a/$', 'delete_u_abort', name='delete_u_abort'),
    url(r'^p/(\d+)/e/$', 'edit_project', name='edit_project'),
    url(r'^p/(\d+)/e/u/$', 'manage_users', name='manage_users'),
    url(r'^p/(\d+)/e/u/(\d+)/$', 'manage_users', name='manage_users'),
    url(r'^p/(\d+)/e/o/$', 'add_owner', name='add_owner'),
    url(r'^p/(\d+)/e/r/$', 'owner_resign', name='owner_resign'),
    url(r'^p/s/$', 'start_project', name='start_project'),
    url(r'^p/(\d+)/p/$', 'start_project', name='start_project'),
    url(r'^p/(\d+)/d/$', 'delete_project', name='delete_project'),
    url(r'^p/(\d+)/d/t/$', 'delete_p_timer', name='delete_p_timer'),
    url(r'^p/(\d+)/d/c/$', 'delete_p_confirm', name='delete_p_confirm'),
    url(r'^p/(\d+)/d/a/$', 'delete_p_abort', name='delete_p_abort'),
    url(r'^p/(\d+)/w/$', 'startwork', name='startwork'),
    url(r'^p/(\d+)/f/$', 'finishwork', name='finishwork'),
    url(r'^e/p/$', 'edit_profile', name='edit_profile'),
    url(r'^e/p/p/$', 'edit_password', name='edit_password'),
    url(r'^e/l/$', 'edit_langs', name='edit_langs'),
    url(r'^about/$', 'about_us', name='about_us'),
    url(r'^contact/$', 'contact', name='contact'),
    )

peerwire/reporting/urls.py
from django.conf.urls import patterns, include, url

from reporting import views

urlpatterns = patterns('reporting.views',
    url(r'^p/(\d+)/$', 'r_project', name='r_project'),
    url(r'^u/(\d+)/$', 'r_user', name='r_user'),
)

peerwire/projects/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.mail import send_mail
from functions import *

# Global difficulty levels
LEVEL_CHOICES = (
    ('Beginner', 'Beginner'),
    ('Easy', 'Easy'),
    ('Medium', 'Medium'),
    ('Advanced', 'Advanced'),
    ('Expert', 'Expert'),
)

class Lang(models.Model):
    name = models.CharField(max_length=30)

    def __unicode__(self):
        return self.name

class User(AbstractUser):
    avatar = models.ImageField(upload_to='avatars', blank=True)
    description = models.TextField(blank=True)
    del_t = models.DateField(blank=True, null=True)
    premium = models.BooleanField(default=False)

    def __unicode__(self):
        if self.first_name:
            if self.last_name:
                return self.username + ' - ' + self.get_full_name()
            else:
                return self.username + ' - ' + self.first_name
        else:
            return self.username

class Project(models.Model):
    name = models.CharField(max_length=50)
    owners = models.ManyToManyField(User, related_name='projects_owned')
    description = models.TextField(blank=True)
    langs = models.ManyToManyField(Lang, blank=True)
    users = models.ManyToManyField(
        User, related_name='projects_workingon', blank=True
        )
    level = models.CharField(
        max_length=8,
        choices=LEVEL_CHOICES,
        blank=False, default=''
        )
    STATUS_CHOICES = (
        ('Inactive', 'Inactive'),
        ('Active', 'Active'),
    )
    status = models.CharField(
        max_length= 8,
        choices=STATUS_CHOICES,
        blank=False, default='Active'
        )
    parent = models.ForeignKey('self', blank=True, null=True)
    SEEKING_CHOICES = (
        ('No', 'Not seeking for help'),
        ('Yes', 'Seeking for help'),
    )
    seeking = models.CharField(
        max_length=3,
        choices=SEEKING_CHOICES,
        blank=False, default='No'
        )
    value = models.IntegerField(default=0)
    pub_date = models.DateField(auto_now_add=True)
    change_date = models.DateField(auto_now=True)
    del_q = models.ManyToManyField(User, blank=True, related_name='del_q')
    del_t = models.DateField(blank=True, null=True)

    def project_tree(self):
        return get_project_tree(self, '', [], 0, 1)

    def project_root(self):
        return get_project_root(self, [])

    def __unicode__(self):
        return get_project_path(self)

class UserLang(models.Model):
    lang = models.ForeignKey(Lang)
    user = models.ForeignKey(User)
    level = models.CharField(max_length=8, choices=LEVEL_CHOICES)

    def __unicode__(self):
        return self.lang.name

class Credit(models.Model):
    user = models.ForeignKey(User)
    project = models.ForeignKey(Project)
    ack = models.IntegerField(default=0)

peerwire/projects/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth import authenticate, login
from django.forms.models import modelformset_factory
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers
from django.contrib.auth.hashers import check_password, make_password

from projects.models import *
from news.models import News
from projects.forms import *
from projects.texts import *
from projects.functions import markdown

import datetime
import Image

def index(request):
    trending_projects = Project.objects.all().order_by('-value')[:5]
    news = News.objects.all().order_by('-pub_date')[:10]
    context = {
        'trending_projects': trending_projects,
        'news': news,
        }
    if request.user.is_authenticated():
        proper = Project.objects.filter(
            seeking='Yes',
            status='Active'
            ).exclude(users__in=[request.user,])
        userlangs = request.user.userlang_set.all().values('lang')
        r_langs = proper.filter(langs__in=userlangs).distinct()
        context['recommended'] = r_langs.order_by('users')[:5]
    return render(request, 'projects/index.html', context)

def projectpage(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if project.status == 'Active':
        project.value += 1
        project.save()
    context = {'project': project, 'desc': markdown(project.description)}
    return render(request, 'projects/projectpage.html', context)

def edit_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.owners.all():
        return redirect('projects:projectpage', project.pk)
    if request.method == 'POST':
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            form.save()
            messages.success(request, changes_saved)
            return redirect('projects:projectpage', project.pk)
    else:
        form = ProjectForm(instance=project)
    context = {'form': form, 'project': project}
    return render(request, 'projects/edit_project.html', context)

def manage_users(request, project_id, user_id=None):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.owners.all():
        return redirect('projects:projectpage', project.pk)
    if user_id:
        user = get_object_or_404(User, pk=user_id)
        if user in project.users.all():
            project.users.remove(user)
            messages.success(request, user_removed)
            return redirect('projects:manage_users', project.pk)
    context = {'project': project}
    return render(request, 'projects/manage_users.html', context)

def add_owner(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.owners.all():
        return redirect('projects:projectpage', project.pk)
    if request.method == 'POST':
        form = InputForm(request.POST)
        if form.is_valid():
            try:
                user = User.objects.get(
                    username=form.cleaned_data.get('username')
                    )
            except:
                messages.error(request, user_not_found)
                return redirect('projects:add_owner', project_id)
            if user not in project.owners.all():
                project.owners.add(user)
                request.user.save()
                messages.success(request, owner_added)
            else:
                messages.error(request, user_already_owner)
                return redirect('projects:add_owner', project_id)
            return redirect('projects:projectpage', project.pk)
    else:
        form = InputForm()
    context = {'form': form, 'project': project}
    return render(request, 'projects/add_owner.html', context)

def owner_resign(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.owners.all():
        return redirect('projects:projectpage', project.pk)
    if not project.owners.all().count() > 1:
        messages.error(request, last_owner)
        return redirect('projects:projectpage', project.pk)
    project.owners.remove(request.user)
    request.user.save()
    messages.success(request, owner_resigned)
    return redirect('projects:projectpage', project.pk)

def start_project(request, parent_id=None):
    if not request.user.is_authenticated():
        return redirect('auth_login')
    if request.method == 'POST':
        project = Project()
        form = ProjectForm(request.POST, instance=project)
        if form.is_valid():
            p = form.save(commit=False)
            p.save()
            if parent_id:
                par = get_object_or_404(Project, pk=parent_id)
                if request.user not in par.owners.all():
                    return redirect('projects:projectpage', par.pk)
                p.parent = par
                p.save()
            p.owners.add(request.user)
            form.save()
            messages.success(request, project_started)
            return redirect('projects:projectpage', project.pk)
    else:
        form = ProjectForm()
    return render(request, 'projects/start_project.html', {'form': form})

def delete_project(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user not in project.owners.all():
        return redirect('projects:projectpage', project.pk)
    if request.method == 'POST':
        if request.POST.get('delete'):
            if project.owners.all().count() <= 1:
                project.delete()
                messages.success(request, del_p_complete)
                return redirect('projects:index')
            for o in project.owners.all():
                if o != request.user:
                    project.del_q.add(o)
                    project.del_t = (
                        datetime.date.today() + datetime.timedelta(days=7)
                    )
                    project.save()
                    o.email_user(
                        'Your project %s is queued for deletion' % project,
                        project_del % (
                            project,
                            str(reverse(
                                'projects:delete_p_confirm',
                                args=(project.pk,)
                            )),
                            str(reverse(
                                'projects:delete_p_abort',
                                args=(project.pk,)
                            )),
                            str(project.del_t)
                        )
                    )
            return redirect('projects:delete_p_timer', project.pk)
    return render(request, 'projects/confirmation.html', {'project': project})

def delete_p_timer(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    return render(request, 'projects/delete_timer.html', {'project': project})

def delete_p_confirm(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user in project.del_q.all():
        project.del_q.remove(request.user)
        if project.del_q.all().count() <= 0:
            project.delete()
            messages.success(request, del_p_complete)
        else:
            messages.success(request, del_p_confirm)
    return redirect('projects:index')

def delete_p_abort(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if request.user in project.del_q.all():
        for u in project.del_q.all():
            project.del_q.remove(u)
        project.del_t = None
        project.save()
        messages.success(request, del_p_abort)
        return redirect('projects:projectpage', project.pk)
    return redirect('projects:index')

def startwork(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if not request.user.is_authenticated():
        return redirect('projects:projectpage', project.pk)
    if ((project.seeking == 'Yes' or request.user in project.owners.all()) and
        request.user not in project.users.all()):
        project.users.add(request.user)
        project.save()
        messages.success(request, work_started)
    return redirect('projects:projectpage', project.pk)

def finishwork(request, project_id):
    project = get_object_or_404(Project, pk=project_id)
    if not request.user.is_authenticated():
        return redirect('projects:projectpage', project.pk)
    if request.user in project.users.all():
        project.users.remove(request.user)
        project.save()
        messages.success(request, work_finished)
    return redirect('projects:projectpage', project.pk)

def profilepage(request, profile_id):
    profile = get_object_or_404(User, pk=profile_id)
    context = {'profile': profile, 'desc': markdown(profile.description)}
    return render(request, 'projects/profilepage.html', context)

def edit_profile(request):
    if not request.user.is_authenticated():
        return redirect('projects:index')
    profile = get_object_or_404(User, pk=request.user.pk)
    if request.method == 'POST':
        form = UserForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            if 'email' in form.changed_data:
                request.user.email_user(
                    'Your email address has been changed',
                    'Your email address has been changed to %s.' %
                        form.cleaned_data.get('email')
                    )
            form.save()
            if 'avatar' in form.changed_data and form.cleaned_data.get(
                'avatar'
                ):
                im = Image.open(profile.avatar.path)
                if im.size[0] < im.size[1]:
                    ratio = im.size[1] / float(im.size[0])

templates/projects/add_owner.html
{% extends 'base.html' %}

{% block title %}Manage Workers - {% endblock %}

{% block content %}
    <div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Manage Workers
    </div>
    <div class="subcontainer_c">
        <form method="POST" action=".">
            <table>
                {% csrf_token %}
                {{ form.as_table }}
                <tr><td></td><td>
                <input type="submit" value="Add" />
                </td></tr>
            </table>
        </form>
        <p class="center">
        <a href="{% url 'projects:projectpage' project.pk %}">Back to project</a>
        </p>
    </div>
    </div>
{% endblock %}

templates/projects/confirmation.html
{% extends 'base.html' %}

{% block title %}Are you sure? - {% endblock %}

{% block content %}
<div class="subcontainer sc_full">
    <div class="subcontainer_h">
        {% if project %}
            Are you sure you want to delete "{{ project }}"?
        {% else %}
            Are you sure you want to delete your profile?
        {% endif %}
    </div>
    <div class="subcontainer_c center">
        <p>
        {% if project %}
            Deleting this project will delete all subprojects as well. If you
            are not the sole owner of this project, the other owners will have
            7 days to abort the deletion.
        {% else %}
            Deleting your profile will delete all projects solely owned by you.
            You will have 7 days to abort the deletion.
        {% endif %}
        </p>
        <p>
        <form action="." method="POST">
        {% csrf_token %}
        <input type="submit" name="delete" class="red" value="I am sure"/>
        </form>
        </p>
    </div>
</div>
{% endblock %}

templates/projects/edit_profile.html
{% extends 'base.html' %}

{% block title %}Edit Profile - {% endblock %}

{% block content %}
    <div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Edit Profile
    </div>
    <div class="subcontainer_c">
        <form action="." method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table>
            {{ form.as_table }}
            <tr><td></td><td><input type="submit" value="Save" /></td></tr>
            </table>
        </form>
    </div>
    </div>
    <div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Change Password
    </div>
    <div class="subcontainer_c center">
        <p>
        <form action="{% url 'projects:edit_password' %}" method="POST">
            <table>
            {% csrf_token %}
            {{ pw_form.as_table }}
            <tr><td></td><td><input type="submit" value="Save" /></td></tr>
            </table>
        </form>
        </p>
    </div>
    </div>
    <div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Delete Profile
    </div>
    <div class="subcontainer_c center">
        <p>
        If you click this button, there will be a another confirmation page.
        </p>
        <p>
        <form action="{% url 'projects:delete_profile' user.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" class="red" value="Delete Profile" />
        </form>
        </p>
    </div>
    </div>
{% endblock %}

templates/projects/index.html
{% extends 'base.html' %}

{% block title %}{% endblock %}

{% block content %}
<div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Welcome
    </div>
    <div class="subcontainer_c">
        <div class="half" style="float: left">
            <p>Peerwire is a platform for collaborative work on projects,
            wether you are starting a project and need qualified people
            or are looking for work on someone's project.</p>
            <p>Click <a href="{% url 'projects:about_us' %}">here</a> to learn more.</p>
        </div>
        <div class="half" style="float: right">
        <p>
            <form method="GET" action="{% url 'projects:start_project' %}">
                <input type="submit" value="Start a new project" style="margin-right: 5px" />
            </form>
            <p>or search for existing ones</p>
        <form method="GET" action="{% url 'haystack:haystack_search' %}">
            <input type="text" name="q" placeholder="Search" style="width: 100%" />
            </form>
        </p>
        </div>
    </div>
</div>
<div class="subcontainer sc_small right">
    <div class="subcontainer_h">
        News
    </div>
    <div class="subcontainer_c">
        <ol>
        {% for post in news %}
            <li><a href="{% url 'news:newspage' post.id %}">{{ post.title }}</a></li>
        {% empty %}
            No News
        {% endfor %}
        </ol>
    </div>
</div>
{% if user.is_authenticated %}
    <div class="subcontainer sc_large left">
        <div class="subcontainer_h">
            Recommended projects
        </div>
        <div class="subcontainer_c">
            <ol>
            {% for project in recommended %}
                <li><a href="{% url 'projects:projectpage' project.id %}">{{ project }}</a></li>
            {% empty %}
                    No recommended projects
            {% endfor %}
            </ol>
        </div>
    </div>
{% endif %}
<div class="subcontainer sc_large left">
    <div class="subcontainer_h">
        Trending projects
    </div>
    <div class="subcontainer_c">
        <ol>
        {% for project in trending_projects %}
            <li><a href="{% url 'projects:projectpage' project.id %}">{{ project }}</a></li>
        {% empty %}
            No trending projects
        {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}

templates/projects/profilepage.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ profile.username }} - {% endblock %}

{% block content %}
    {% if user == profile %}
        <div class="subcontainer sc_small right">
            <div class="subcontainer_h">
                Admin
            </div>
            <div class="subcontainer_c">
            <ul>
                <li><a href="{% url 'projects:edit_profile' %}">Edit Profile</a></li>
                <li><a href="{% url 'projects:edit_langs' %}">Edit Languages</a></li>
            </ul>
            </div>
        </div>
    {% endif %}
    <div class="subcontainer sc_large left">
        <div class="subcontainer_h">
            {% if profile.first_name %}
                {{ profile.get_full_name }}
            {% else %}
                {{ profile.username }}
            {% endif %}
            {% if profile.first_name %}
                ({{ profile.username }})
            {% endif %}
        </div>
        <div class="subcontainer_c pure_li img_width ul_a">
            {% if profile.avatar %}
                <div class="avatar" style="background-image: url({{ profile.avatar.url }})">&nbsp;</div>
            {% else %}
                <div class="avatar" style="background-image: url({% static 'avatar.svg' %})">&nbsp;</div>
            {% endif %}
            {% autoescape off %}
            {{ desc|default:"<p>No description given.</p>" }}
            {% endautoescape %}
            <div class="da">
                <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                <!-- Peerwire Responsive -->
                <ins class="adsbygoogle"
                     style="display:block"
                     data-ad-client="ca-pub-5757275602398953"
                     data-ad-slot="1400122950"
                     data-ad-format="auto"></ins>
                <script>
                (adsbygoogle = window.adsbygoogle || []).push({});
                </script>
            </div>
            <p>Date joined: {{ profile.date_joined|date:"Y-m-d" }}</p>
            <p>
            <form action="{% url 'reporting:r_user' profile.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" name="delete" class="red" value="Report user"/>
            </form>
            </p>
        </div>
    </div>
    <div class="subcontainer sc_small right">
        <div class="subcontainer_h">
            Languages
        </div>
        <div class="subcontainer_c">
            <ul>
            {% for l in profile.userlang_set.all %}
                <li><a href="{% url 'haystack:haystack_search' %}?q={{ l|urlencode }}">{{ l }}</a> ({{ l.level }})</li>
            {% empty %}
                None
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="subcontainer sc_small right">
        <div class="subcontainer_h">
            Projects owned ({{ profile.projects_owned.count }})
        </div>
        <div class="subcontainer_c">
            <ul>
            {% for p in profile.projects_owned.all %}
                <li><a href="{% url 'projects:projectpage' p.pk %}" title="{{ p }}">{{ p.name }}</a></li>
            {% empty %}
                None
            {% endfor %}
            </ul>
        </div>
    </div>
    <div class="subcontainer sc_small right">
        <div class="subcontainer_h">
            Working on ({{ profile.projects_workingon.count }})
        </div>
        <div class="subcontainer_c">
            <ul>
            {% for p in profile.projects_workingon.all %}
                <li><a href="{% url 'projects:projectpage' p.pk %}" title="{{ p }}">{{ p.name }}</a></li>
            {% empty %}
                None
            {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}

templates/projects/projectpage.html
{% extends 'base.html' %}
{% load get_range %}

{% block title %}{{ project }} - {% endblock %}

{% block content %}
{% if user in project.owners.all %}
    <div class="subcontainer sc_small right">
        <div class="subcontainer_h">
            Admin
        </div>
        <div class="subcontainer_c">
        <ol>
            <li><a href="{% url 'projects:edit_project' project.pk %}">Edit Project</a></li>
            <li><a href="{% url 'projects:manage_users' project.pk %}">Manage workers</a></li>
            <li><a href="{% url 'projects:add_owner' project.pk %}">Add owner</a></li>
            <li><a href="{% url 'projects:start_project' project.pk %}">Start Subproject</a></li>
            {% if project.owners.all.count > 1 %}
                <li><a href="{% url 'projects:owner_resign' project.pk %}">Resign from project</a></li>
            {% endif %}
            <li><a href="{% url 'projects:delete_project' project.pk %}">Delete Project</a></li>
        </ol>
        </div>
    </div>
{% endif %}
<div class="subcontainer sc_large left">
    <div class="subcontainer_h">
        {% for pp in project.project_root %}
            <a href="{% url 'projects:projectpage' pp.pk %}">{{ pp.name }}</a> /
        {% endfor %}
        {{ project.name }}
    </div>
    <div class="subcontainer_c pure_li img_width ul_a">
        {% autoescape off %}{{ desc|default:"<p>No description given.</p>" }}{% endautoescape %}
        <div class="da">
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Peerwire Responsive -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-5757275602398953"
                 data-ad-slot="1400122950"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
        {% if project.langs.exists %}
            <p>Languages used:<br />
            {{ project.langs.all|join:", " }}</p>
        {% endif %}
        <p>
        Project started: {{ project.pub_date|date:"Y-m-d" }}<br />
        Last change: {{ project.change_date|date:"Y-m-d" }}<br />
        Currently {{ project.status|lower }},
        {% if project.seeking == 'No' %}
            not
        {% endif %}
        seeking for help
        </p>
        <p>
        <form action="{% url 'reporting:r_project' project.pk %}" method="POST">
        {% csrf_token %}
        <input type="submit" name="delete" class="red" value="Report project"/>
        </form>
        </p>
    </div>
</div>
{% if user.is_authenticated %}
    {% if project.seeking == 'Yes' and user not in project.users.all %}
        <div class="subcontainer sc_small right">
            <div class="subcontainer_h">
                Work
            </div>
            <div class="subcontainer_c">
                <a href="{% url 'projects:startwork' project.pk %}">Work on this project</a>
            </div>
        </div>
    {% elif user in project.owners.all and user not in project.users.all %}
        <div class="subcontainer sc_small right">
            <div class="subcontainer_h">
                Work
            </div>
            <div class="subcontainer_c">
                <a href="{% url 'projects:startwork' project.pk %}">Work on this</a>
            </div>
        </div>
    {% elif user in project.users.all %}
        <div class="subcontainer sc_small right">
            <div class="subcontainer_h">
                Work
            </div>
            <div class="subcontainer_c">
                <a href="{% url 'projects:finishwork' project.pk %}">Stop working on this</a>
            </div>
        </div>
    {% endif %}
{% endif %}
<div class="subcontainer sc_small right">
    <div class="subcontainer_h">
        Owners
    </div>
    <div class="subcontainer_c">
        <ul>
        {% for u in project.owners.all %}
            <li><a href="{% url 'projects:profilepage' u.pk %}">{{ u }}</a></li>
        {% empty %}
            None
        {% endfor %}
        </ul>
    </div>
</div>
<div class="subcontainer sc_small right">
    <div class="subcontainer_h">
        Workers
    </div>
    <div class="subcontainer_c">
        <ul>
        {% for u in project.users.all %}
            <li><a href="{% url 'projects:profilepage' u.pk %}">{{ u }}</a></li>
        {% empty %}
            None
        {% endfor %}
        </ul>
    </div>
</div>
<div class="subcontainer sc_small right">
    <div class="subcontainer_h">
        Tree
    </div>
    <div class="subcontainer_c">
        <ol>
        {% for array in project.project_tree %}
            {% for b in array %}
                    {% autoescape off %}
                        <li><span class="mono">{{ b.1 }}</span>{% endautoescape %}<a href="{% url 'projects:projectpage' b.0.pk %}">{{ b.0.name }}</a></li>
            {% endfor %}
        {% endfor %}
        </ol>
    </div>
</div>
{% endblock %}