peerwire/news/urls.py
from django.conf.urls import patterns, include, url

from news import views
from news.feeds import NewsFeed

urlpatterns = patterns('news.views',
    url(r'^$', 'index', name='index'),
    url(r'^(\d+)/$', 'newspage', name='newspage'),
    url(r'^f/$', NewsFeed(), name='newsfeed'),
    )

peerwire/peerwire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView

from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

sqs = SearchQuerySet().facet('status').facet('seeking').facet('level')

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^a/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^a/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^a/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^a/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^a/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^a/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    # url(r'^a/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm_uidb36,
    #     name='password_reset_confirm'),
    url(r'^a/', include('registration.backends.default.urls')),
    url(r'^s/$', FacetedSearchView(
        form_class=FacetedSearchForm,
        searchqueryset=sqs
        ), name='haystack_search'),
    url(r'^s/', include('haystack.urls', namespace='haystack')),
    url(r'^n/', include('news.urls', namespace='news')),
    url(r'^r/', include('reporting.urls', namespace='reporting')),
    url(r'^', include('projects.urls', namespace='projects')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peerwire/news/models.py
from django.db import models
import markdown

class News(models.Model):
    title = models.CharField(max_length=50)
    text =  models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.title

    def get_markdown(self):
        return markdown.markdown(
            self.text,
            safe_mode='escape',
            output_format='html5',
            extensions=['codehilite(noclasses=true,pygments_style=friendly)']
            )

peerwire/news/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_headers

from news.models import News

@cache_page(60 * 15)
@vary_on_headers('Cookie')
def index(request):
    news_list = News.objects.all().order_by('-pub_date')
    paginator = Paginator(news_list, 5)
    page = request.GET.get('p')
    try:
        news = paginator.page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)
    context = {'news': news}
    return render(request, 'news/index.html', context)

@cache_page(60 * 60)
@vary_on_headers('Cookie')
def newspage(request, news_id):
    news = get_object_or_404(News, pk=news_id)
    context = {'news': news}
    return render(request, 'news/newspage.html', context)

templates/news/index.html
{% extends 'base.html' %}

{% block title %}News - {% endblock %}

{% block content %}
    <div class="subcontainer sc_full">
        {% for post in news %}
            <div class="subcontainer_h">
                <a href="{% url 'news:newspage' post.pk %}">{{ post.title }}</a>
            </div>
            <div class="subcontainer_c pure_li">
                <span style="font-size: 12px">{{ post.pub_date }}</span>
                {% autoescape off %}
                {{ post.get_markdown }}
                {% endautoescape %}
            </div>
        {% empty %}
            <p>No news here.</p>
        {% endfor %}
    </div>
    <div class="subcontainer sc_full">
        <div class="subcontainer_c">
            Did someone say <a href="{% url 'news:newsfeed' %}">RSS</a>?
        </div>
    </div>
{% endblock %}

templates/news/newspage.html
{% extends 'base.html' %}

{% block title %}{{ news.title }} - {% endblock %}

{% block content %}
    <div class="subcontainer sc_full">
        <div class="subcontainer_h">
            {{ news.title }}
        </div>
        <div class="subcontainer_c pure_li">
            <span style="font-size: 12px">{{ news.pub_date }}</span>
            {% autoescape off %}
            {{ news.get_markdown }}
            {% endautoescape %}
        </div>
    </div>
{% endblock %}

templates/news/projectpage.html
{% extends 'base.html' %}

{% block title %}{{ news.title }} - {% endblock %}

{% block content %}
    <div class="subcontainer sc_full">
        <div class="subcontainer_h">
            {{ news.title }}
        </div>
        <div class="subcontainer_c">
            {{ news.text|linebreaksbr }}
            <br />
            <span style="font-size: 12px">{{ news.pub_date }}</span>
        </div>
    </div>
{% endblock %}