peerwire/news/urls.py
from django.conf.urls import patterns, include, url

from news import views
from news.feeds import NewsFeed

urlpatterns = patterns('news.views',
    url(r'^$', 'index', name='index'),
    url(r'^(\d+)/$', 'newspage', name='newspage'),
    url(r'^f/$', NewsFeed(), name='newsfeed'),
    )

peerwire/peerwire/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from haystack.forms import FacetedSearchForm
from haystack.query import SearchQuerySet
from haystack.views import FacetedSearchView

from django.contrib.auth import views as auth_views
from django.contrib import admin
admin.autodiscover()

sqs = SearchQuerySet().facet('status').facet('seeking').facet('level')

urlpatterns = patterns('',
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^a/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^a/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^a/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^a/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^a/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^a/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),
    # url(r'^a/password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
    #     auth_views.password_reset_confirm_uidb36,
    #     name='password_reset_confirm'),
    url(r'^a/', include('registration.backends.default.urls')),
    url(r'^s/$', FacetedSearchView(
        form_class=FacetedSearchForm,
        searchqueryset=sqs
        ), name='haystack_search'),
    url(r'^s/', include('haystack.urls', namespace='haystack')),
    url(r'^n/', include('news.urls', namespace='news')),
    url(r'^r/', include('reporting.urls', namespace='reporting')),
    url(r'^', include('projects.urls', namespace='projects')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

peerwire/projects/urls.py
from django.conf.urls import patterns, include, url

from projects import views

urlpatterns = patterns('projects.views',
    url(r'^$', 'index', name='index'),
    url(r'^p/(\d+)/$', 'projectpage', name='projectpage'),
    url(r'^u/(\d+)/$', 'profilepage', name='profilepage'),
    url(r'^u/(\d+)/d/$', 'delete_profile', name='delete_profile'),
    url(r'^u/(\d+)/d/a/$', 'delete_u_abort', name='delete_u_abort'),
    url(r'^p/(\d+)/e/$', 'edit_project', name='edit_project'),
    url(r'^p/(\d+)/e/u/$', 'manage_users', name='manage_users'),
    url(r'^p/(\d+)/e/u/(\d+)/$', 'manage_users', name='manage_users'),
    url(r'^p/(\d+)/e/o/$', 'add_owner', name='add_owner'),
    url(r'^p/(\d+)/e/r/$', 'owner_resign', name='owner_resign'),
    url(r'^p/s/$', 'start_project', name='start_project'),
    url(r'^p/(\d+)/p/$', 'start_project', name='start_project'),
    url(r'^p/(\d+)/d/$', 'delete_project', name='delete_project'),
    url(r'^p/(\d+)/d/t/$', 'delete_p_timer', name='delete_p_timer'),
    url(r'^p/(\d+)/d/c/$', 'delete_p_confirm', name='delete_p_confirm'),
    url(r'^p/(\d+)/d/a/$', 'delete_p_abort', name='delete_p_abort'),
    url(r'^p/(\d+)/w/$', 'startwork', name='startwork'),
    url(r'^p/(\d+)/f/$', 'finishwork', name='finishwork'),
    url(r'^e/p/$', 'edit_profile', name='edit_profile'),
    url(r'^e/p/p/$', 'edit_password', name='edit_password'),
    url(r'^e/l/$', 'edit_langs', name='edit_langs'),
    url(r'^about/$', 'about_us', name='about_us'),
    url(r'^contact/$', 'contact', name='contact'),
    )

templates/about_us.html
{% extends 'base.html' %}

{% block title %}About us - {% endblock %}

{% block content %}
<div class="subcontainer sc_full">
    <div class="subcontainer_h">
        About Peerwire
    </div>
    <div class="subcontainer_c">
        <p>Peerwire is a platform about organizing your project and helping the right people find them. It is
        mainly targeted at software projects, but may be used in any way possible. Let's play through an
        example:</p>

        <p>Steve and Bob want to make a mobile game inspired by Tetris, which they want to call "Megablox".
        But making a game is too much for to do on their own, so they need to find other people interested
        in joining.</p>

        {% load staticfiles %}
        <img src="{% static 'intro.png' %}" style="display: block; margin: auto; max-width: 100%" />

        <h3 style="color:black; font-weight: normal">TL,DR;</h3>
        <p>You can use an infinite amount of subprojects divide and conquer your project, isolating single tasks
        and attract specialists for the ones you need help with. This way, you generate what we call the
        project tree, which allows you to drill down into more and more specific areas of your project.</p>
    </div>
</div>
{% endblock %}

templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>{% block title %}{% endblock %}Peerwire</title>
    <link rel="stylesheet" href="{% static 'stylesheet.css' %}" type="text/css; charset=utf-8" />
    <link rel="stylesheet" href="{% static 'stylesheet_responsive.css' %}" type="text/css; charset=utf-8" />
    <link rel="icon" href="{% static 'favicon.png' %}" type="image/png" />
    <link href='http://fonts.googleapis.com/css?family=Cantarell:400,400italic,700,700italic' rel='stylesheet' type='text/css' />
    <script type="text/javascript" src="{% static 'jquery-1.11.0.min.js' %}"></script>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-38330260-5', 'peerwire.org');
      ga('send', 'pageview');

    </script>
    <script>
    $("document").ready(function(){
        setTimeout(function(){
            $("div.messages").slideUp("slow");
        }, 2000);
    });
    </script>
    {% block head %}{% endblock %}
</head>
<body>
    {% if messages %}
        {% for message in messages %}
            <div class="messages msg_{{ message.level }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    <div id="container">
        <div id="header">
            <div>
                <a id="home-link" href="/">Peerwire</a>
            </div>
            <div id="menu">
                <menu id="main_menu" type="toolbar">
                    <li class="menu_button">
                    <a href="{% url 'haystack_search' %}" target="_self">search</a>
                    </li>
                    <li class="menu_button">
                    <a href="{% url 'news:index' %}" target="_self">news</a>
                    </li>
                {% if user.is_authenticated %}
                    <li class="menu_button">
                    <a href="{% url 'projects:profilepage' user.pk %}" target="_self">my profile</a>
                    </li>
                    <li class="menu_button">
                    <a href="{% url 'auth_logout' %}" target="_self">logout</a>
                    </li>
                {% else %}
                    <li class="menu_button">
                    <a href="{% url 'auth_login' %}" target="_self">register / login</a>
                    </li>
                {% endif %}
                </menu>
            </div>
            <div id="account">
                {% if user.is_authenticated %}
                    welcome back,
                    {% if user.first_name %}
                        {{ user.first_name }}
                    {% else %}
                        {{ user.username }}
                    {% endif %}
                {% else %}
                    welcome, guest
                {% endif %}
            </div>
        </div>
        <div id="content">
            {% block content %}
                This should not be visible. Content-block is missing.
            {% endblock %}
        </div>
    </div>
    <div class="ad ad_right">
        <div style="position: absolute">
            <p>You use Adblock?</p>
            <p>That's fine, but please consider whitelisting Peerwire, as we
            can only survive by displaying ads to you.</p>
        </div>
        <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Peerwire Sidebar -->
        <ins class="adsbygoogle"
             style="display:inline-block;width:160px;height:600px"
             data-ad-client="ca-pub-5757275602398953"
             data-ad-slot="3376414952"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
        </script>
    </div>
    <div id="footer">
        &copy; 2014 peerwire |
        <a href="{% url 'projects:about_us' %}">about us</a> |
        <a href="{% url 'projects:contact' %}">contact</a>
    </div>
</body>
</html>

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact - {% endblock %}

{% block content %}
<div class="subcontainer sc_full">
    <div class="subcontainer_h">
        Contact
    </div>
    <div class="subcontainer_c">
        <h3>You can reach us here:</h3>

        <h4>Online</h4>
        <p>
        <a href="mailto:postmaster@peerwire.org">postmaster@peerwire.org</a>
        </p>

        <h4>Offline</h4>
        <p>
        Peerwire<br />
        Robin Schroer<br />
        Landshuter Str. 10<br />
        47249 Duisburg<br />
        Germany
        </p>

    </div>
</div>
{% endblock %}

templates/skeleton.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <!-- TODO: stylesheets -->
    <title>{% block title %}{% endblock %}Peerwire</title>
</head>
<body>
    <a href="{% url 'projects:index' %}">Home</a>
    {% if user.is_authenticated %}
        Welcome back,
        {% if user.first_name %}
            {{ user.first_name }}
        {% else %}
            {{ user.username }}
        {% endif %}
        <a href="{% url 'logout' %}">Logout</a>
    {% else %}
        Welcome, Guest
        <a href="{% url 'login' %}">Login</a>
    {% endif %}
    <br>
    {% block content %}
        This should not be visible. Content-block is missing.
    {% endblock %}
</body>
</html>